--CREATE DATABASE [IES300-T]
USE [IES300-T]

-- ================================
--        DROP DAS TABELAS
-- ================================
/*
   DROP TABLE dbo.G07_CONSUMO;
   DROP TABLE dbo.G07_ITEM_FORMULA;
   DROP TABLE dbo.G07_ITEM_PEDIDOS;
   DROP TABLE dbo.G07_ITEM_RECURSO;
   DROP TABLE dbo.G07_PEDIDOS;
   DROP TABLE dbo.G07_PRODUCAO;
   DROP TABLE dbo.G07_FORMULAS;
   DROP TABLE dbo.G07_ESTOQUE;
   DROP TABLE dbo.G07_LOCAIS;
   DROP TABLE dbo.G07_CLIENTES;
   DROP TABLE dbo.G07_RECURSOS;
   DROP TABLE dbo.G07_PRODUTOS;
*/
-- ================================

CREATE TABLE G07_CLIENTES(
CLI_ID					INTEGER IDENTITY(1,1) PRIMARY KEY,
CLI_RAZAO_SOCIAL		VARCHAR(50),
CLI_CNPJ				VARCHAR(18), 
CLI_NOME_RESPONSAVEL	VARCHAR(50),
CLI_EMAIL				VARCHAR(100),
CLI_TELEFONE			VARCHAR(14),
CLI_CEP					VARCHAR(9),
CLI_NOME_LOGRADOURO		VARCHAR(100),
CLI_TIPO_LOGRADOURO		VARCHAR(30),
CLI_CIDADE				VARCHAR(50),
CLI_BAIRRO				VARCHAR(50),
CLI_COMPLEMENTO			VARCHAR(100),
CLI_NUMERO_LOGRADOURO	VARCHAR(10),
CLI_UF					VARCHAR(2)
)

CREATE TABLE G07_PRODUTOS(
PRODUTO_ID				INTEGER IDENTITY(1,1) PRIMARY KEY,
PRODUTO_NOME			VARCHAR(60),
PRODUTO_DESCRICAO		VARCHAR(50),
PRODUTO_CATEGORIA		VARCHAR(30),
PRODUTO_STATUS			NUMERIC(1,0),
PRODUTO_TIPO			VARCHAR(15),
CONSTRAINT CHECK_PRODUTO_TIPO CHECK (PRODUTO_TIPO IN ('MATERIA-PRIMA','PRODUTO ACABADO')),
CONSTRAINT CHECK_PRODUTO_STATUS CHECK (PRODUTO_STATUS IN (0,1)),
)

CREATE TABLE G07_PEDIDOS(
PEDIDO_ID				INTEGER IDENTITY(1,1) PRIMARY KEY,
PEDIDO_DATA				DATETIME,
PEDIDO_DATA_ENTREGA		DATE,
PEDIDO_STATUS			VARCHAR(11),
CLI_ID					INTEGER FOREIGN KEY REFERENCES G07_CLIENTES(CLI_ID),
CONSTRAINT CHEC_PEDIDO_STATUS CHECK (PEDIDO_STATUS IN ('EM PROCESSO','CANCELADO','FINALIZADO'))
)

CREATE TABLE G07_ITEM_PEDIDOS(
ITEM_ID					INTEGER IDENTITY(1,1) PRIMARY KEY,
ITEM_QTD				INTEGER,
PEDIDO_ID				INTEGER FOREIGN KEY REFERENCES G07_PEDIDOS(PEDIDO_ID),
PRODUTO_ID				INTEGER FOREIGN KEY REFERENCES G07_PRODUTOS(PRODUTO_ID)
)

CREATE TABLE G07_FORMULAS(
FORMULA_ID				INTEGER IDENTITY(1,1) PRIMARY KEY,
FORMULA_DESCRICAO		VARCHAR(50)
)

CREATE TABLE G07_ITEM_FORMULA(
FORMULA_ITEM_QTD		INTEGER,
FORMULA_ID				INTEGER FOREIGN KEY REFERENCES G07_FORMULAS(FORMULA_ID),
PRODUTO_ID				INTEGER FOREIGN KEY REFERENCES G07_PRODUTOS(PRODUTO_ID),
)

CREATE TABLE G07_RECURSOS(
RECURSO_ID				INTEGER IDENTITY(1,1) PRIMARY KEY,
RECURSO_TIPO			VARCHAR(50),
RECURSO_NOME			VARCHAR(50),
RECURSO_QTD				INTEGER,
RECURSO_STATUS			VARCHAR(10),
CONSTRAINT CHECK_RECURSO_STATUS CHECK(RECURSO_STATUS IN ('ATIVADO','DESATIVADO'))
)

CREATE TABLE G07_PRODUCAO(
PRODUCAO_ID				INTEGER IDENTITY(1,1) PRIMARY KEY,
PRODUCAO_DATA_INICIO	DATE,
PRODUCAO_DATA_FIM		DATE,
PRODUCAO_DATA_ALTER		DATETIME,
PRODUCAO_QTD			INTEGER,
PRODUCAO_STATUS			VARCHAR(9),
PRODUCAO_DATA_REG		DATETIME,
PRODUCAO_OBS			VARCHAR(100),
PEDIDO_ID				INTEGER FOREIGN KEY REFERENCES G07_PEDIDOS(PEDIDO_ID),
PRODUTO_ID				INTEGER FOREIGN KEY REFERENCES G07_PRODUTOS(PRODUTO_ID),
FORMULA_ID				INTEGER FOREIGN KEY REFERENCES G07_FORMULAS(FORMULA_ID),
CONSTRAINT CHECK_PRODUCAO_STATUS CHECK (PRODUCAO_STATUS IN ('ABERTO','CANCELADO','ENCERRADO'))
)

CREATE TABLE G07_ITEM_RECURSO
(
RECURSO_ITEM_QTD		INTEGER,
RECURSO_ID				INTEGER FOREIGN KEY REFERENCES G07_RECURSOS(RECURSO_ID),
PRODUCAO_ID				INTEGER FOREIGN KEY REFERENCES G07_PRODUCAO(PRODUCAO_ID)
)

CREATE TABLE G07_LOCAIS (
LOCAL_ID				INTEGER IDENTITY(1,1) PRIMARY KEY,
LOCAL_DESCRICAO			VARCHAR(50),
LOCAL_CAPACIDADE		INTEGER
)

CREATE TABLE G07_ESTOQUE (
ESTOQUE_QTD				INTEGER,
LOCAL_ID				INTEGER FOREIGN KEY REFERENCES G07_LOCAIS(LOCAL_ID),
PRODUTO_ID				INTEGER FOREIGN KEY REFERENCES G07_PRODUTOS(PRODUTO_ID)
)


CREATE TABLE G07_CONSUMO(
CONSUMO_ID				INTEGER IDENTITY(1,1) PRIMARY KEY,
CONSUMO_DATA			DATE,
CONSUMO_QTD				INTEGER,
LOCAL_ID				INTEGER FOREIGN KEY REFERENCES G07_LOCAIS(LOCAL_ID),
PRODUTO_ID				INTEGER FOREIGN KEY REFERENCES G07_PRODUTOS(PRODUTO_ID),
PRODUCAO_ID				INTEGER FOREIGN KEY REFERENCES G07_PRODUCAO(PRODUCAO_ID)
)