USE [IES300-T]

/*SELECT PRODUTO_NOME FROM dbo.G07_PRODUTOS
	WHERE PRODUTO_ID = 23;
SELECT PRODUTO_ID, PRODUTO_NOME FROM dbo.G07_PRODUTOS;
SELECT * FROM dbo.G07_ITEM_PEDIDOS WHERE PEDIDO_ID = 3;*/

-- ================================
--       DELETE REGISTROS
-- ================================
/*
DELETE FROM dbo.G07_CONSUMO;
DELETE FROM dbo.G07_ITEM_FORMULA;
DELETE FROM dbo.G07_ITEM_PEDIDOS;
DELETE FROM dbo.G07_ITEM_RECURSO;
DELETE FROM dbo.G07_PEDIDOS;
DELETE FROM dbo.G07_PRODUCAO;
DELETE FROM dbo.G07_FORMULAS;
DELETE FROM dbo.G07_ESTOQUE;
DELETE FROM dbo.G07_LOCAIS;
DELETE FROM dbo.G07_CLIENTES;
DELETE FROM dbo.G07_RECURSOS;
DELETE FROM dbo.G07_PRODUTOS;
*/
-- ================================

INSERT INTO G07_PRODUTOS(PRODUTO_NOME, PRODUTO_DESCRICAO,PRODUTO_CATEGORIA,PRODUTO_STATUS,PRODUTO_TIPO)
VALUES	('ALÇA DE EMBUTIR REFORÇO CONTÍNUO'     ,'TESTE', 'ALÇAS'  , 1, 'PRODUTO ACABADO'),
		('ALÇA DE EMBUTIR MINI REFORÇO CONTÍNUO','TESTE', 'ALÇAS'  , 1, 'PRODUTO ACABADO'),
		('ALÇA DE EMBUTIR'                      ,'TESTE', 'ALÇAS'  , 1, 'PRODUTO ACABADO'),
		('ALÇA DE EMBUTIR MINI'                 ,'TESTE', 'ALÇAS'  , 1, 'PRODUTO ACABADO'),
		('CABIDE PARA PASTA LATERAL'            ,'TESTE', 'ALÇAS'  , 1, 'PRODUTO ACABADO'),
		('CANETAFIX'                            ,'TESTE', 'ALÇAS'  , 1, 'PRODUTO ACABADO'),
		('CD-FIX'                               ,'TESTE', 'ALÇAS'  , 1, 'PRODUTO ACABADO'),
		('GRAMPO INTELIGENTE ARQFIX'            ,'TESTE', 'ALÇAS'  , 1, 'PRODUTO ACABADO'),
		('METAL'                                ,'TESTE', 'METAL'  , 1, 'MATERIA-PRIMA'),
		('POLIPROPILENO'                        ,'TESTE', 'INSUMO' , 1, 'MATERIA-PRIMA'),
		('POLIETILENO LDPE'                     ,'TESTE', 'INSUMO' , 1, 'MATERIA-PRIMA'),
		('POLIETILENO HDPE'                     ,'TESTE', 'INSUMO' , 1, 'MATERIA-PRIMA'),
		('POLIETILENO PEAD-HDPE'                ,'TESTE', 'INSUMO' , 1, 'MATERIA-PRIMA'),
		('POLIETILENO PEUBD-ULDPE'              ,'TESTE', 'INSUMO' , 1, 'MATERIA-PRIMA'),
		('POLIETILENO PEUAPM-UHMWPE'            ,'TESTE', 'INSUMO' , 1, 'MATERIA-PRIMA'),
		('ACRILONITRILO BUTADIENO ESTIRENO'     ,'TESTE', 'INSUMO' , 1, 'MATERIA-PRIMA'),
		('POLICLORETO DE VINILA FLEXÍVEL'       ,'TESTE', 'INSUMO' , 1, 'MATERIA-PRIMA'),
		('POLIOXIMETILENO HOMOPOLÍMETRO'        ,'TESTE', 'INSUMO' , 1, 'MATERIA-PRIMA'),
		('POLIAMIDA'                            ,'TESTE', 'INSUMO' , 1, 'MATERIA-PRIMA'),
		('POLIBUTIRENO TERAFTALATO'             ,'TESTE', 'INSUMO' , 1, 'MATERIA-PRIMA'),
		('ACETATO DE CELULOSE'                  ,'TESTE', 'INSUMO' , 1, 'MATERIA-PRIMA'),
		('POLIOXIFENILENO'                      ,'TESTE', 'INSUMO' , 1, 'MATERIA-PRIMA');

INSERT INTO G07_LOCAIS(LOCAL_CAPACIDADE,LOCAL_DESCRICAO)
VALUES	(13500,'LOCAL 1')

INSERT INTO G07_ESTOQUE(ESTOQUE_QTD,LOCAL_ID,PRODUTO_ID)
VALUES	(1000,1,1),
		(1000,1,2),
		(1000,1,3),
		(1000,1,4),
		(1000,1,5),
		(1000,1,6),
		(1000,1,7),
		(1000,1,8),
		(1000,1,9),
		(1000,1,10),
		(1000,1,11),
		(1000,1,12),
		(1000,1,13),
		(1000,1,14),
		(1000,1,15),
		(1000,1,16),
		(1000,1,17),
		(1000,1,18),
		(1000,1,19),
		(1000,1,20),
		(1000,1,21),
		(1000,1,22);

INSERT INTO G07_CLIENTES(CLI_RAZAO_SOCIAL,CLI_CNPJ,CLI_NOME_RESPONSAVEL, CLI_EMAIL, CLI_TELEFONE,CLI_CEP,CLI_NOME_LOGRADOURO,CLI_CIDADE,CLI_BAIRRO,CLI_COMPLEMENTO,CLI_NUMERO_LOGRADOURO,CLI_UF)
VALUES	('INDUSTRIA DE PLASTICO CELCO'     ,'78.425.986/0036-15', 'EDUARDO GONÇALVES'  ,'SABERINFINITO@HOTMAIL.COM' , '(11)95555-5555','07170-000', 'AV. TIRADENTES', 'SÃO PAULO', 'BOM RETIRO', 'PRAÇA', '1602', 'SP'),
		('WES WES CIA','78.425.986/0036-15','WESLEY MANTOVANI'  , 'NESQUIK@HOTMAIL.COM','(11)95555-5555','07170-000','AV. TIRADENTES' ,'SÃO PAULO', 'BOM RETIRO'    , 'PRAÇA'    ,                        '1602', 'SP'),
		('CAFÉ COM FRANCIS LTDA'           ,'78.425.986/0036-15', 'FRANCISCO ANTUNES'  ,'SABERINFINITO@HOTMAIL.COM' ,'(11)95555-5555' ,'07170-000', 'AV. TIRADENTES', 'SÃO PAULO', 'BOM RETIRO', 'PRAÇA', '1602', 'SP'),
		('FATEC-SP'                        ,'78.425.986/0036-15', 'JOÃO PEDRO PIO'     ,'SABERINFINITO@HOTMAIL.COM' ,'(11)95555-5555' ,'07170-000', 'AV. TIRADENTES', 'SÃO PAULO', 'BOM RETIRO', 'PRAÇA', '1602', 'SP'),
		('GOODSTORAGE'                     ,'78.425.986/0036-15', 'FABIO COSTA'        ,'SABERINFINITO@HOTMAIL.COM' ,'(11)95555-5555' ,'07170-000', 'AV. TIRADENTES', 'SÃO PAULO', 'BOM RETIRO', 'PRAÇA', '1602', 'SP'),
		('COMPRAKI'                        ,'78.425.986/0036-15', 'CINTHIA SARAIVA'    ,'SABERINFINITO@HOTMAIL.COM' ,'(11)95555-5555' ,'07170-000', 'AV. TIRADENTES', 'SÃO PAULO', 'BOM RETIRO', 'PRAÇA', '1602', 'SP'),
		('BOLACHÃO'                        ,'78.425.986/0036-15', 'GABRIEL RITTER'     ,'SABERINFINITO@HOTMAIL.COM' ,'(11)95555-5555' ,'07170-000', 'AV. TIRADENTES', 'SÃO PAULO', 'BOM RETIRO', 'PRAÇA', '1602', 'SP'),
		('CAA LTDA'                        ,'78.425.986/0036-15', 'ANDRÉ LUIS'         ,'SABERINFINITO@HOTMAIL.COM' ,'(11)95555-5555' ,'07170-000', 'AV. TIRADENTES', 'SÃO PAULO', 'BOM RETIRO', 'PRAÇA', '1602', 'SP'),
		('CANTINA DO AMARAL'               ,'78.425.986/0036-15', 'ALEXANDRE AMARAL'   ,'SABERINFINITO@HOTMAIL.COM' ,'(11)95555-5555' ,'07170-000', 'AV. TIRADENTES', 'SÃO PAULO', 'BOM RETIRO', 'PRAÇA', '1602', 'SP'),
		('NIANTIC'                         ,'78.425.986/0036-15', 'VICTOR GABRIEL'     ,'SABERINFINITO@HOTMAIL.COM' ,'(11)95555-5555' ,'07170-000', 'AV. TIRADENTES', 'SÃO PAULO', 'BOM RETIRO', 'PRAÇA', '1602', 'SP'),
		('ACHE'                            ,'78.425.986/0036-15', 'GABRIELE FASOLO'    ,'SABERINFINITO@HOTMAIL.COM' ,'(11)95555-5555' ,'07170-000', 'AV. TIRADENTES', 'SÃO PAULO', 'BOM RETIRO', 'PRAÇA', '1602', 'SP');

INSERT INTO G07_RECURSOS(RECURSO_TIPO, RECURSO_NOME, RECURSO_QTD, RECURSO_STATUS)
VALUES	('MÁQUINA', 'INJETORA DE PLÁSTICO MANUAL'     ,3,'ATIVADO'),
		('MÁQUINA', 'INJETORA DE PLÁSTICO PORTA MOLDE',3,'ATIVADO'),
		('MÁQUINA', 'INJETORA DE PLÁSTICO SEMERARO'   ,3,'ATIVADO'),
		('MÁQUINA', 'INJETORA VERTICAL COM MOLDE'     ,3,'ATIVADO'),
		('MOLDE'  , 'MOLDE-A1'                        ,3,'ATIVADO'),
		('MOLDE'  , 'MOLDE-A2'                        ,3,'ATIVADO'),
		('MOLDE'  , 'MOLDE-C30'                       ,3,'ATIVADO'),
		('MOLDE'  , 'MOLDE-D2'                        ,3,'ATIVADO');


/*SELECT A.PEDIDO_ID, A.PRODUTO_ID, B.PRODUTO_NOME FROM G07_ITEM_PEDIDOS A INNER JOIN G07_PRODUTOS B INNER JOIN G07_PEDIDOS C ON A.PRODUTO_ID = B.PRODUTO_ID AND C.PEDIDO_STATUS='EM PROCESSO';


--SELECIONA TODOS OS PRODUTOS QUE TEM UM PEDIDO E TEM FORMULA
SELECT B.PRODUTO_ID,B.PRODUTO_NOME, C.PEDIDO_ID FROM G07_ITEM_PEDIDOS A 
INNER JOIN G07_PRODUTOS B ON (A.PRODUTO_ID = B.PRODUTO_ID) 
INNER JOIN G07_PEDIDOS C ON (C.PEDIDO_ID = A.PEDIDO_ID)
INNER JOIN G07_ITEM_FORMULA D ON(D.PRODUTO_ID = B.PRODUTO_ID) 
WHERE C.PEDIDO_STATUS = 'EM PROCESSO' AND B.PRODUTO_STATUS=1 AND B.PRODUTO_TIPO='PRODUTO ACABADO'

SELECT * FROM G07_PRODUCAO

--SELECIONAR O PEDIDO EM RELAÇÃO AO PRODUTO SELECIONADO
SELECT A.PEDIDO_ID FROM G07_ITEM_PEDIDOS A
INNER JOIN G07_PEDIDOS B ON (A.PEDIDO_ID = B.PEDIDO_ID)
WHERE A.PRODUTO_ID = 7 AND B.PEDIDO_STATUS = 'EM PROCESSO'*/

